   <%@ include file="header.jsp" %> 
   				<ul class="nav navbar-nav navbar-right">
					<li><a href="SIGN IN.html">Sign In </a></li> 
				 <li><a href="SIGN UP.html">Sign Up</a></li> 
						
				</ul>
			</div>
		</div>
		<br>

		<div>
			<ul class="nav navbar-nav navbar-left">
				<li class="dropdown"><a href="#" class="dropdown-toggle"
					data-toggle="dropdown">Categories <span class="caret"></span></a>
					<ul class="dropdown-menu">
						<li><a href="#">Indoor Lightings</a></li>
						<li><a href="#">flat panel</a></li>
						<li><a href="#">surface panel</a></li>
						<li><a href="HOME.html">external lunar</a></li>
						<li><a href="HOME.html">led strip</a></li>
						<li><a href="HOME.html">color changing led panel light</a></li>
						<li><a href="HOME.html">Outdoor Lightings</a></li>
						<li><a href="HOME.html">pathway</a></li>
						<li><a href="HOME.html">street & roadway</a></li>
						<li><a href="HOME.html">decorative street & roadway</a></li>
						<li><a href="HOME.html">parking structure</a></li>
						<li><a href="HOME.html">high mast</a></li>
					</ul></li>
			</ul>
			<ul>

				<div>

					<form class="bs-example bs-example-form" role="form">
						<div class="row">
							<div class="col-lg-6">
								<div class="input-group">
									<input type="text" class="form-control"> <span
										class="input-group-btn">
										<button class="btn btn-default" type="button">Go!</button>
									</span>

								</div>
							</div>
						</div>
					</form>
				</div>
			</ul>
		</div>
	</nav>
   	
<div class="thumbnail">
<p><pre>

<center><b>THE LIGHTS WAGON Privacy Policy</b></center>

<b>TERMS OF USE</b>

This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.

This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of www.ledshopindia.com website.

The domain name www.ledshopindia.com (hereinafter referred to as "Website") is owned by THE LIGHTS WAGON with its registered office at A-25, Govind Nagar, Opp. BSNL Exchange, Ajaramar Chowk, Adajan, Surat-395009, and Gujarat-India (hereinafter referred to as <b>THE LIGHTS WAGON</b>.

Your use of the Website and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Website including the applicable policies which are incorporated herein by way of reference. If you transact on the Website, You shall be subject to the policies that are applicable to the Website for such transaction. By mere use of the Website, You shall be contracting with THE LIGHTS WAGON and these terms and conditions including the policies constitute your binding obligations, with THE LIGHTS WAGON.

For the purpose of these Terms of Use, wherever the context so requires "You" or "User" shall mean any natural or legal person who has agreed to become a buyer on the Website by providing Registration Data while registering on the Website as Registered User using the computer systems. THE LIGHTS WAGON allows the User to surf the Website or making purchases without registering on the Website. The term "We", "Us", "Our" shall mean THE LIGHTS WAGON

When You use any of the services provided by Us through the Website, including but not limited to, (e.g. Product Reviews), You will be subject to the rules, guidelines, policies, terms, and conditions applicable to such service, and they shall be deemed to be incorporated into this Terms of Use and shall be considered as part and parcel of this Terms of Use. We reserve the right, at our sole discretion, to change, modify, add or remove portions of these Terms of Use, at any time without any prior written notice to you. It is your responsibility to review these Terms of Use periodically for updates / changes. Your continued use of the Website following the posting of changes will mean that you accept and agree to the revisions. As long as you comply with these Terms of Use, We grant you a personal, non-exclusive, non-transferable, limited privilege to enter and use the Website.

ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESETERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING. By impliedly or expressly accepting these Terms of Use, You also accept and agree to be bound by THE LIGHTS WAGON Policies ((including but not limited to Privacy Policy available on privacy policy) as amended from time to time.

<b>MEMBERSHIP ELIGIBILITY</b>

Use of the Website is available only to persons who can form legally binding contracts under Indian Contract Act, 1872. Persons who are "in competent to contract" within the meaning of the Indian Contract Act, 1872 including minors, un-discharged insolvents etc. are not eligible to use the Website. If you are a minor i.e. under the age of 18 years, you shall not register as a User of the THE LIGHTS WAGON website and shall not transact on or use the website. As a minor if you wish to use or transact on website, such use or transaction may be made by your legal guardian or parents on the Website. THE LIGHTS WAGON reserves the right to terminate your membership and / or refuse to provide you with access to the Website if it is brought to THE LIGHTS WAGON's notice or if it is discovered that you are under the age of 18 years.

YOUR ACCOUNT AND REGISTRATION OBLIGATIONS

If you use the Website, You shall be responsible for maintaining the confidentiality of your Display Name and Password and you shall be responsible for all activities that occur under your Display Name and Password. You agree that if You provide any information that is untrue, inaccurate, not current or incomplete or We have reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with the this Terms of Use, We shall have the right to indefinitely suspend or terminate or block access of your membership on the Website and refuse to provide You with access to the Website.

<b>COMMUNICATIONS</b>

When You use the Website or send emails or other data, information or communication to us, You agree and understand that You are communicating with Us through electronic records and You consent to receive communications via electronic records from Us periodically and as and when required. We may communicate with you by email or by such other mode of communication, electronic or otherwise.

PLATFORM FOR TRANSACTION AND COMMUNICATION

The Website is a platform that Users utilize to meet and interact with one another for their transactions. THE LIGHTS WAGON is not and cannot be a party to or control in any manner any transaction between the Website's Users.

Henceforward:

1. All commercial/contractual terms are offered by and agreed to between Buyers and THE LIGHTS WAGON alone. The commercial/contractual terms include without limitation price, shipping costs, payment methods, payment terms, date, period and mode of delivery, warranties related to products and services and after sales services related to products and services.

2. THE LIGHTS WAGON does not make any representation or Warranty as to specifics (such as quality, value, salability, etc) of the products or services proposed to be sold or offered to be sold or purchased on the Website. THE LIGHTS WAGON does not implicitly or explicitly support or endorse the sale or purchase of any products or services on the Website. THE LIGHTS WAGON accepts no liability for any errors or omissions, whether on behalf of itself or third parties.

4. THE LIGHTS WAGON does not make any representation or warranty as to the item-specifics (such as legal title, creditworthiness, identity, etc) of any of its Users. You are advised to independently verify the bonafides of any particular User that you choose to deal with on the Website and use your best judgment in that behalf.

7. The Website is only a platform that can be utilized by Users to reach a larger base to buy products or services. THE LIGHTS WAGON is not responsible for unsatisfactory or delayed performance of services or damages or delays as a result of products which are out of stock, unavailable or back ordered.

8. You shall independently agree upon the manner and terms and conditions of delivery, payment, insurance etc. with the THE LIGHTS WAGON(s) that you transact with.

Disclaimer: Pricing on any product(s) as is reflected on the Website may due to some technical issue, typographical error or product information published by THE LIGHTS WAGON may be incorrectly reflected and in such an event THE LIGHTS WAGON may cancel such your order(s).

Please note that there could be risks in dealing with underage persons or people acting under false pretence.

<b>CHARGES</b>

Membership on the Website is free for buyers. THE LIGHTS WAGON does not charge any fee for browsing and buying on the Website. THE LIGHTS WAGON reserves the right to change its Fee Policy from time to time. In particular, THE LIGHTS WAGON may at its sole discretion introduce new services and modify some or all of the existing services offered on the Website. In such an event THE LIGHTS WAGON reserves the right to introduce fees for the new services offered or amend/introduce fees for existing services, as the case may be. Changes to the Fee Policy shall be posted on the Website and such changes shall automatically become effective immediately after they are posted on the Website. Unless otherwise stated, all fees shall be quoted in Indian Rupees. You shall be solely responsible for compliance of all applicable laws including those in India for making payments to THE LIGHTS WAGON .

<b>USE OF THE WEBSITE</b>

You agree, undertake and confirm that your use of Website shall be strictly governed by the following binding principles:

1. You shall not host, display, upload, modify, publish, transmit, update or share any information which:

(a) belongs to another person and to which You does not have any right to;

(b) is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libellous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever; or unlawfully threatening or unlawfully harassing including but not limited to "indecent representation of women" within the meaning of the Indecent Representation of Women (Prohibition) Act, 1986;

(c) is misleading in any way;

(d) is patently offensive to the online community, such as sexually explicit content, or content that promotes obscenity, paedophilia, racism, bigotry, hatred or physical harm of any kind against any group or individual;

(e) harasses or advocates harassment of another person;

(f) involves the transmission of "junk mail", "chain letters", or unsolicited mass mailing or "spamming";

(g) promotes illegal activities or conduct that is abusive, threatening, obscene, defamatory or libelous;

(h) infringes upon or violates any third party's rights [including, but not limited to, intellectual property rights, rights of privacy (including without limitation unauthorized disclosure of a person's name, email address, physical address or phone number) or rights of publicity];

(i) promotes an illegal or unauthorized copy of another person's copyrighted work below for instructions, such as providing pirated computer programs or links to them, providing information to circumvent manufacture-installed copy-protect devices, or providing pirated music or links to pirated music files;

(j) contains restricted or password-only access pages, or hidden pages or images (those not linked to or from another accessible page);

(l) provides instructional information about illegal activities such as making or buying illegal weapons, violating someone's privacy, or providing or creating computer viruses;

(m) contains video, photographs, or images of another person (with a minor or an adult).

(n) tries to gain unauthorized access or exceeds the scope of authorized access to the Website or to profiles, blogs, communities, account information, bulletins, friend request, or other areas of the Website or solicits passwords or personal identifying information for commercial or unlawful purposes from other users;

(o) engages in commercial activities and/or sales without Our prior written consent such as contests, sweepstakes, barter, advertising and pyramid schemes, or the buying or selling of "virtual" products related to the Website. Throughout this Terms of Use, THE LIGHTS WAGON's prior written consent means a communication coming from THE LIGHTS WAGON's Legal Department, specifically in response to Your request, and specifically addressing the activity or conduct for which You seek authorization;

(p) solicits gambling or engages in any gambling activity which We, in Our sole discretion, believes is or could be construed as being illegal;

(q) interferes with another USER's use and enjoyment of the Website or any other individual's User and enjoyment of similar services;

(r) refers to any website or URL that, in Our sole discretion, contains material that is inappropriate for the Website or any other website, contains content that would be prohibited or violates the letter or spirit of these Terms of Use.

(s) harm minors in any way;

(t) infringes any patent, trademark, copyright or other proprietary rights or third party's trade secrets or rights of publicity or privacy or shall not be fraudulent or involve the sale of counterfeit or stolen products;

(u) violates any law for the time being in force;

(v) deceives or misleads the addressee/ users about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;

(w) impersonate another person;

(x) contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource; or contains any trojan horses, worms, time bombs, cancelbots, easter eggs or other computer programming routines that may damage, detrimentally interfere with, diminish value of, surreptitiously intercept or expropriate any system, data or personal information;

(y) threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nation.

(z) shall not be false, inaccurate or misleading;

(aa) shall not, directly or indirectly, offer, attempt to offer, trade or attempt to trade in any item, the dealing of which is prohibited or restricted in any manner under the provisions of any applicable law, rule, regulation or guideline for the time being in force.

(ab) shall not create liability for Us or cause Us to lose (in whole or in part) the services of Our internet service provider ("ISPs") or other suppliers;

2. You shall not use any "deep-link", "page-scrape", "robot", "spider" or other automatic device, program, algorithm or methodology, or any similar or equivalent manual process, to access, acquire, copy or monitor any portion of the Website or any Content, or in any way reproduce or circumvent the navigational structure or presentation of the Website or any Content, to obtain or attempt to obtain any materials, documents or information through any means not purposely made available through the Website. We reserve our right to bar any such activity.

3. You shall not attempt to gain unauthorized access to any portion or feature of the Website, or any other systems or networks connected to the Website or toany server, computer, network, or to any of the services offered on or through the Website, by hacking, password "mining" or any other illegitimate means.

4. You shall not probe, scan or test the vulnerability of the Website or any network connected to the Website nor breach the security or authentication measures on the Website or any network connected to the Website. You may not reverse look-up, trace or seek to trace any information on any other User of or visitor to Website, or any other customer, including any account on the Website not owned by You, to its source, or exploit the Website or any service or information made available or offered by or through the Website, in any way where the purpose is to reveal any information, including but not limited to personal identification or information, other than Your own information, as provided for by the Website.

5. You shall not make any negative, denigrating or defamatory statement(s) or comment(s) about Us or the brand name or domain name used by Us including the terms THE LIGHTS WAGON, or otherwise engage in any conduct or action that might tarnish the image or reputation, of THE LIGHTS WAGON or THE LIGHTS WAGONs on platform or otherwise tarnish or dilute any THE LIGHTS WAGON's trade or service marks, trade name and/or goodwill associated with such trade or service marks, trade name as may be owned or used by us. You agree that you will not take any action that imposes an unreasonable or disproportionately large load on the infrastructure of the Website or THE LIGHTS WAGON's systems or networks, or any systems or networks connected to THE LIGHTS WAGON.

6. You agree not to use any device, software or routine to interfere or attempt to interfere with the proper working of the Website or any transaction being conducted on the Website, or with any other person's use of the Website.

7. You may not forge headers or otherwise manipulate identifiers in order to disguise the origin of any message or transmittal you send to Us on or through the Website or any service offered on or through the Website. You may not pretend that you are, or that you represent, someone else, or impersonate any other individual or entity.

8. You may not use the Website or any content for any purpose that is unlawful or prohibited by these Terms of Use, or to solicit the performance of any illegal activity or other activity which infringes the rights of THE LIGHTS WAGON and / or others.

9. You shall at all times ensure full compliance with the applicable provisions of the Information Technology Act, 2000 and rules there under as applicable and as amended from time to time and also all applicable Domestic laws, rules and regulations (including the provisions of any applicable Exchange Control Laws or Regulations in Force) and International Laws, Foreign Exchange Laws, Statutes, Ordinances and Regulations (including, but not limited to Sales Tax/VAT, Income Tax, Octroi, Service Tax, Central Excise, Custom Duty, Local Levies) regarding Your use of Our service and Your listing, purchase, solicitation of offers to purchase, and sale of products or services. You shall not engage in any transaction in an item or service, which is prohibited by the provisions of any applicable law including exchange control laws or regulations for the time being in force.

10. Solely to enable Us to use the information You supply Us with, so that we are not violating any rights You might have in Your Information, You agree to grant Us a non-exclusive, worldwide, perpetual, irrevocable, royalty-free, sub-licensable (through multiple tiers) right to exercise the copyright, publicity, database rights or any other rights You have in Your Information, in any media now known or not currently known, with respect to Your Information. We will only use Your information in accordance with the Terms of Use and Privacy Policy applicable to use of the Website.

11. From time to time, you shall be responsible for providing information relating to the products or services proposed to be sold by you. In this connection, you undertake that all such information shall be accurate in all respects. You shall not exaggerate or over emphasize the attributes of such products or services so as to mislead other Users in any manner.

12. You shall not engage in advertising to, or solicitation of, other Users of the Website to buy or sell any products or services, including, but not limited to, products or services related to that being displayed on the Website or related to us. You may not transmit any chain letters or unsolicited commercial or junk email to other Users via the Website. It shall be a violation of these Terms of Use to use any information obtained from the Website in order to harass, abuse, or harm another person, or in order to contact, advertise to, solicit, or sell to another person other than Us without Our prior explicit consent. In order to protect Our Users from such advertising or solicitation, We reserve the right to restrict the number of messages or emails which a user may send to other Users in any 24-hour period which We deems appropriate in its sole discretion. You understand that we have the right at all times to disclose any information (including the identity of the persons providing information or materials on the Website) as necessary to satisfy any law, regulation or valid governmental request. This may include, without limitation, disclosure of the information in connection with investigation of alleged illegal activity or solicitation of illegal activity or in response to a lawful court order or subpoena. In addition, We can (and You hereby expressly authorize Us to) disclose any information about You to law enforcement or other government officials, as we, in Our sole discretion, believe necessary or appropriate in connection with the investigation and/or resolution of possible crimes, especially those that may involve personal injury.

14. It is possible that other user (including unauthorized users or "hackers") may post or transmit offensive or obscene materials on the Website and that You may be involuntarily exposed to such offensive and obscene materials. It also is possible for others to obtain personal information about you due to your use of the Website, and that the recipient may use such information to harass or injure you. We does not approve of such unauthorized uses, but by using the Website You acknowledge and agree that We are not responsible for the use of any personal information that You publicly disclose or share with others on the Website. Please carefully select the type of information that you publicly disclose or share with others on the Website.

15. THE LIGHTS WAGON shall have all the rights to take necessary action and claim damages that may occur due to your involvement/participation in any way on your owner through group/s of people, intentionally or unintentionally in DoS/DDoS (Distributed Denial of Services).

<b>PRIVACY</b>

We view protection of your privacy as a very important principle. We understand clearly that You and Your Personal Information is one of Our most important assets. We store and process Your Information including any sensitive financial information collected (as defined under the Information Technology Act, 2000), if any, on computers that may be protected by physical as well as reasonable technological security measures and procedures in accordance with Information Technology Act 2000 and Rules there under. Our current Privacy Policy is available at privacy policy. If you object to Your Information being transferred or used in this way please do not use Website.

We and our affiliates will share / sell / transfer / license / covey some or all of your personal information with another business entity should we (or our assets) plan to merge with or are acquired by that business entity, or re-organization, amalgamation, restructuring of business or for any other reason whatsoever. Should such a transaction or situation occur, the other business entity or the new combined entity will be required to follow the privacy policy with respect to your personal information. Once you provide your information to us, you provide such information to us and our affiliate and we and our affiliate may use such information to provide you various services with respect to your transaction whether such transaction are conducted on www.THE LIGHTS WAGON.com or with third party merchant's or third party merchant's website.

<b>DISCLAIMER OF WARRANTIES AND LIABILITY</b>

This Website, all the materials and products and services, included on or otherwise made available to You through this site are provided on "as is" and "as available" basis without any representation or warranties, express or implied except otherwise specified in writing. Without prejudice to the forgoing paragraph, THE LIGHTS WAGON does not warrant that:

-> This Website will be constantly available, or available at all; or

-> The information on this Website is complete, true, accurate or non-misleading.

THE LIGHTS WAGON will not be liable to you in any way or in relation to the Contents of, or use of, or otherwise in connection with, the Website. THE LIGHTS WAGON does not warrant that this site; information, Content, materials, product (including software) or services included on or otherwise made available to You through the Website; their servers; or electronic communication sent from Us are free of viruses or other harmful components.

Nothing on Website constitutes, or is meant to constitute, advice of any kind. All the Products sold on Website are governed by different state laws and if THE LIGHTS WAGON is unable to deliver such Products due to implications of different state laws, THE LIGHTS WAGON will return or will give credit for the amount (if any) received in advance by THE LIGHTS WAGON from the sale of such Product that could not be delivered to You.

You will be required to enter a valid phone number while placing an order on the Website. By registering your phone number with us, You consent to be contacted by Us via phone calls and/or SMS notifications, in case of any order or shipment or delivery related updates. We will not use your personal information to initiate any promotional phone calls or SMS.

<b>SERVICES</b>

Payment Facility for Buyers:

-> You, as a Buyer, understand that upon initiating a Transaction You are entering into a legally binding and enforceable contract with the THE LIGHTS WAGON to purchase the products and /or services from the THE LIGHTS WAGON using the Payment Facility, and You shall pay the Transaction Price through Your Issuing Bank to the THE LIGHTS WAGON using Payment Facility. A Buyer can cancel order within 24 hours.

-> You, as a Buyer, may agree with the THE LIGHTS WAGON through electronic communication and electronic records and using the automated features as may be provided by Payment Facility on any extension / increase in the Dispatch and/or Delivery time and the Transaction shall stand amended to such extent. Any such extension / increase of Dispatch / Delivery time or subsequent novation / variation of the Transaction should be in compliance with Payment Facility Rules and Policies.

-> You, as a Buyer, shall electronically notify Payment Facility using the appropriate THE LIGHTS WAGON Website features immediately upon Delivery or non Delivery within the time period as provided in Policies. Non notification by You of Delivery or non Delivery within the time period specified in the Policies shall be construed as a deemed Delivery in respect of that Transaction. In case of Cash On Delivery transactions, Buyer is not required to confirm the receipt of products or services.

-> You, as a Buyer, shall be entitled to claim a refund of the Transaction Price (as Your sole and exclusive remedy) in case You do not receive the Delivery within the time period agreed in the Transaction or within the time period as provided in the Policies, whichever is earlier. In case you do not raise a refund claim using Website features within the stipulated time than this would make you ineligible for a refund.

-> You, as a Buyer, understand that the Payment Facility may not be available in full or in part for certain category of products and/or services and/or Transactions as mentioned in the Policies and hence You may not be entitled to a refund in respect of the Transactions for those products and /or services

-> Rrefund, if any, shall be made at the same Issuing Bank from where Transaction Price was received.

-> Refund shall be made in Indian Rupees only and shall be equivalent to the Transaction Price received in Indian Rupees.

-> For electronics payments, refund will be initiated through same online mode within 7 working days

-> Refund shall be conditional and shall be with recourse available to THE LIGHTS WAGON in case of any misuse by Buyer.

-> Refund shall be subject to Buyer complying with Policies.

4. THE LIGHTS WAGON reserves the right to impose limits on the number of Transactions or Transaction Price which THE LIGHTS WAGON may receive from on an individual Valid Credit/Debit/ Cash Card / Valid Bank Account/ and such other infrastructure or any other financial instrument directly or indirectly through payment aggregator or through any such facility authorized by Reserve Bank of India to provide enabling support facility for collection and remittance of payment or by an individual Buyer during any time period, and reserves the right to refuse to process Transactions exceeding such limit.

5. THE LIGHTS WAGON reserves the right to refuse to process Transactions by Buyers with a prior history of questionable charges including without limitation breach of any agreements by Buyer with THE LIGHTS WAGON or breach/violation of any law or any charges imposed by Issuing Bank or breach of any policy.

7. THE LIGHTS WAGON may delay notifying the payment confirmation i.e. informing THE LIGHTS WAGON to Dispatch, if THE LIGHTS WAGON deems suspicious or for Buyers conducting high transaction volumes to ensure safety of the Transaction and Transaction Price. In addition, THE LIGHTS WAGON may hold Transaction Price and THE LIGHTS WAGON may not inform THE LIGHTS WAGON to Dispatch or remit Transaction Price to law enforcement officials (instead of refunding the same to Buyer) at the request of law enforcement officials or in the event the Buyer is engaged in any form of illegal activity.

8. The Buyer and acknowledge that THE LIGHTS WAGON will not be liable for any damages, interests or claims etc. resulting from not processing a Transaction/Transaction Price or any delay in processing a Transaction/Transaction Price which is beyond control of THE LIGHTS WAGON.

Compliance with Laws:

9. Buyer and THE LIGHTS WAGON shall comply with all the applicable laws (including without limitation Foreign Exchange Management Act, 1999 and the rules made and notifications issued there under and the Exchange Control Manual as may be issued by Reserve Bank of India from time to time, Customs Act, Information and Technology Act, 2000 as amended by the Information Technology (Amendment) Act 2008, Prevention of Money Laundering Act, 2002 and the rules made there under, Foreign Contribution Regulation Act, 1976 and the rules made there under, Income Tax Act, 1961 and the rules made there under, Export Import Policy of government of India) applicable to them respectively for using Payment Facility and THE LIGHTS WAGON Website.

Buyer's arrangement with Issuing Bank:

10. All Valid Credit / Debit/ Cash Card/ and other payment instruments are processed using a Credit Card payment gateway or appropriate payment system infrastructure and the same will also be governed by the terms and conditions agreed to between the Buyer and the respective Issuing Bank and payment instrument issuing company.

11. All Online Bank Transfers from Valid Bank Accounts are processed using the gateway provided by the respective Issuing Bank which support Payment Facility to provide these services to the Users. All such Online Bank Transfers on Payment Facility are also governed by the terms and conditions agreed to between Buyer and the respective Issuing Bank.

<b>INDEMNITY</b>

You shall indemnify and hold harmless THE LIGHTS WAGON, its owner, licensee, affiliates, subsidiaries, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorneys' fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, Privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.

<b>APPLICABLE LAW</b>

Terms of Use shall be governed by and interpreted and construed in accordance with the laws of India. The place of jurisdiction shall be exclusively in Surat.

<b>JURISDICTIONAL ISSUES/SALE IN INDIA ONLY</b>

Unless otherwise specified, the material on the Website is presented solely for the purpose of sale in India. THE LIGHTS WAGON makes no representation that materials in the Website are appropriate or available for use in other locations/Countries other than India. Those who choose to access this site from other locations/Countries other than India do so on their own initiative and THE LIGHTS WAGON is not responsible for supply of products/refund for the products ordered from other locations/Countries other than India, compliance with local laws, if and to the extent local laws are applicable.

<b>TRADEMARK, COPYRIGHT AND RESTRICTION</b>

This site is controlled and operated by THE LIGHTS WAGON and products are sold by respective THE LIGHTS WAGONs. All material on this site, including images, illustrations, audio clips, and video clips, are protected by copyrights, trademarks, and other intellectual property rights. Material on Website is solely for your personal, non-commercial use. You must not copy, reproduce, republish, upload, post, transmit or distribute such material in any way, including by email or other electronic means and whether directly or indirectly and You must not assist any other person to do so. Without the prior written consent of the owner, modification of the materials, use of the materials on any other website or networked computer environment or use of the materials for any purpose other than personal, non-commercial use is a violation of the copyrights, trademarks and other proprietary rights, and is prohibited. Any use for which you receive any remuneration, whether in money or otherwise, is a commercial use for the purposes of this clause.

<b>Trademark complaint</b>

THE LIGHTS WAGON respects the intellectual property of others. In case You feel that Your Trademark has been infringed, You can write to THE LIGHTS WAGON at ledshopindia@gmail.com

<b>PRODUCT DESCRIPTION</b>

THE LIGHTS WAGON we do not warrant that Product description or other content of this Website is accurate, complete, reliable, current, or error-free and assumes no liability in this regard.

<b>LIMITATION OF LIABILITY</b>

IN NO EVENT SHALL THE LIGHTS WAGON BE LIABLE FOR ANY SPECIAL, INCIDENTAL, INDIRECT OR CONSEQUENTIAL DAMAGES OF ANY KIND IN CONNECTION WITH THESE TERMS OF USE, EVEN IF USER HAS BEEN INFORMED IN ADVANCE OF THE POSSIBILITY OF SUCH DAMAGES.

<b>POLICIES

PROFANITY POLICY</b>

THE LIGHTS WAGON prohibits the use of language that is racist, hateful, sexual or obscene in nature in a public area.

This policy extends to text within listings, on THE LIGHTS WAGON pages and all other areas of the site that another User may view. If the profane words are part of a title for the item being sold, we allow THE LIGHTS WAGONs to 'blur' out the bulk of the offending word with asterisks (i.e., s*** or f***).

Please report any violations of this policy to the correct area for review:

Report offensive Display Names
Report offensive language in a listing or otherwise
If a feedback comment; or any communication made between Users on the Website; or email communication between Users in relation to transactions conducted on Website contain profanity, please review Our feedback removal policy and submit a request for action/removal.

Disciplinary action may result in the indefinite suspension of a User's account, temporary suspension, or a formal warning.

THE LIGHTS WAGON will consider the circumstances of an alleged policy violation and the user's trading records before taking action.

Violations of this policy may result in a range of actions, including:

Limits placed on account privileges;
Loss of special status;
Account suspension.

<b>RETURN</b>

Definition: 'Return' is defined as the action of giving back the item purchased by the Buyer to the Seller on the THE LIGHTS WAGON website. Following situations may arise:

Item was defective
Item was damaged during the Shipping
Products was / were missing
Wrong item was sent by the Seller.
Return could also result in refund of money in most of the cases.

<b>REPLACEMENT</b>

Definition: Replacement is the action or process of replacing something in place of another. A Buyer can request for replacement if he is not happy with the item, reason being damaged in shipping, Defective item, Item(s) missing, wrong item shipped and the like reasons as above only.

Buyer need to raise the replacement request within 7 days from the date of delivery of products. Once Buyer has raised a replacement request by contacting Us. Once the replacement request has been raised, the following steps shall be followed:

1. Buyer is asked for "Reason for Return".

2. An intimation shall be provided to Seller seeking either "approval" or "rejection" of the replacement request.

Customer is responsible for ensuring that all goods are adequately packed to prevent damage in transit. Any goods found to be physically damaged upon receipt will be returned. For this type of the product Led Shop India will provide the exchange not the refund for the same.

Please send the LED lighting products to:

<b>Returns Department
THE LIGHTS WAGON</b>
XXX
Hyderabad-395009,
Telangana-India
</pre></p>


</div>
<%@ include file="footer.jsp" %>